version: '3'
services:

    redis:
        image: 'redis:latest'

    app:
        build:
            dockerfile: Dockerfile
            context: app
        depends_on:
            - redis
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            # - BIND_ADDR="0.0.0.0"
            # - BIND_PORT=5000

    nginx:
        build:
            dockerfile: Dockerfile
            context: nginx
        depends_on:
            - app
        ports: 
            - 80:80
